apiVersion: v1
kind: Service
metadata:
  name: flint-api
  labels:
    app: flint-api
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
  selector:
    app: flint-api